import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import qrcode from "qrcode-generator";
import {
  ASSURANCE_LABELS,
  documentTypeLabel,
  formatInstantDate,
  type AssuranceLevel,
} from "@/lib/clinical/logic";

/**
 * Server-side PDF rendering for clinical documents. The browser never produces an authoritative PDF.
 *
 * The body is the frozen, hashed, practitioner-approved text — nothing else is added to it. The fixed
 * chrome around it (title, reference, verification QR, signature block, footer) carries only
 * non-clinical information. Output is deterministic for the same input (fixed metadata dates, no random
 * ids), so a document can be regenerated byte-for-byte when issuing is retried.
 */

export type PdfSignatureBlock = {
  practitioner: string;
  registrationNumber: string;
  assurance: AssuranceLevel;
  method: string;
  signedAt: string; // ISO
  reference: string;
};

export type PdfInput = {
  documentId: string;
  documentType: string;
  /** Frozen rendered text (already sanitised by the template engine). */
  content: string;
  issueDate: string | null; // ISO date
  expiresAt: string | null; // ISO timestamp
  verificationUrl: string;
  /** Fixed into the PDF metadata so the output is reproducible (use the approval time). */
  createdAt: Date;
  /** Null before signing: the PDF then states that the document is awaiting signature. */
  signature: PdfSignatureBlock | null;
};

const PAGE = { w: 595.28, h: 841.89 };
const M = { x: 56, top: 64, bottom: 72 };
const BODY = { size: 10.5, lead: 15 };
export const FOOTER_TEXT =
  "This document is electronically issued and may be verified using the verification code.";
export const MAX_PDF_BYTES = 10 * 1024 * 1024;

const SMART: Record<string, string> = {
  "‘": "'",
  "’": "'",
  "“": '"',
  "”": '"',
  "–": "-",
  "—": "-",
  "…": "...",
  " ": " ",
};

/** Standard PDF fonts cover WinAnsi only; anything else becomes "?" instead of failing the render. */
function toWinAnsi(text: string, font: PDFFont): string {
  const supported = new Set(font.getCharacterSet());
  let out = "";
  for (const ch of text.normalize("NFC")) {
    const mapped = SMART[ch] ?? ch;
    for (const c of mapped) out += c === "\n" || supported.has(c.codePointAt(0)!) ? c : "?";
  }
  return out;
}

function wrap(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split("\n")) {
    if (paragraph.trim() === "") {
      lines.push("");
      continue;
    }
    let line = "";
    for (const word of paragraph.split(/\s+/)) {
      const candidate = line ? `${line} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        line = candidate;
        continue;
      }
      if (line) lines.push(line);
      // A single token wider than the line (e.g. a long URL) is split by characters.
      let rest = word;
      while (font.widthOfTextAtSize(rest, size) > maxWidth) {
        let n = rest.length;
        while (n > 1 && font.widthOfTextAtSize(rest.slice(0, n), size) > maxWidth) n--;
        lines.push(rest.slice(0, n));
        rest = rest.slice(n);
      }
      line = rest;
    }
    if (line) lines.push(line);
  }
  return lines;
}

function drawQr(page: PDFPage, text: string, x: number, y: number, size: number) {
  const qr = qrcode(0, "M");
  qr.addData(text);
  qr.make();
  const n = qr.getModuleCount();
  const cell = size / (n + 2); // 1-module quiet zone each side
  page.drawRectangle({ x, y, width: size, height: size, color: rgb(1, 1, 1) });
  for (let r = 0; r < n; r++)
    for (let c = 0; c < n; c++)
      if (qr.isDark(r, c))
        page.drawRectangle({
          x: x + (c + 1) * cell,
          y: y + size - (r + 2) * cell,
          width: cell + 0.05,
          height: cell + 0.05,
          color: rgb(0, 0, 0),
        });
}

export async function renderDocumentPdf(input: PdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const t = (s: string, f: PDFFont = regular) => toWinAnsi(s, f);

  pdf.setTitle(`CannaPlug ${input.documentId}`);
  pdf.setProducer("CannaPlug");
  pdf.setCreator("CannaPlug");
  pdf.setSubject("Electronically issued document");
  pdf.setAuthor("");
  pdf.setKeywords([]);
  pdf.setCreationDate(input.createdAt);
  pdf.setModificationDate(input.createdAt);

  const ink = rgb(0.1, 0.12, 0.1);
  const muted = rgb(0.4, 0.42, 0.4);
  const green = rgb(0.1, 0.4, 0.2);
  const contentWidth = PAGE.w - M.x * 2;
  const pages: PDFPage[] = [];

  const newPage = () => {
    const page = pdf.addPage([PAGE.w, PAGE.h]);
    pages.push(page);
    return page;
  };

  let page = newPage();
  let y = PAGE.h - M.top;

  // Header
  page.drawText("CannaPlug", { x: M.x, y, size: 20, font: bold, color: green });
  y -= 24;
  page.drawText(t(documentTypeLabel(input.documentType), bold), {
    x: M.x,
    y,
    size: 13,
    font: bold,
    color: ink,
  });
  y -= 18;
  const meta = [
    `Document ID: ${input.documentId}`,
    input.issueDate ? `Date: ${formatInstantDate(input.issueDate) ?? input.issueDate}` : null,
    input.expiresAt ? `Valid until: ${formatInstantDate(input.expiresAt)}` : null,
  ]
    .filter(Boolean)
    .join("    ");
  page.drawText(t(meta), { x: M.x, y, size: 9, font: regular, color: muted });
  y -= 10;
  page.drawLine({
    start: { x: M.x, y },
    end: { x: PAGE.w - M.x, y },
    thickness: 0.8,
    color: rgb(0.8, 0.82, 0.8),
  });
  y -= 22;

  // Body (the exact approved text)
  for (const line of wrap(t(input.content), regular, BODY.size, contentWidth)) {
    if (y < M.bottom + BODY.lead) {
      page = newPage();
      y = PAGE.h - M.top;
    }
    if (line) page.drawText(line, { x: M.x, y, size: BODY.size, font: regular, color: ink });
    y -= BODY.lead;
  }

  // Signature + verification block (kept together on one page)
  const blockHeight = 190;
  if (y < M.bottom + blockHeight) {
    page = newPage();
    y = PAGE.h - M.top;
  }
  y -= 14;
  page.drawLine({
    start: { x: M.x, y },
    end: { x: PAGE.w - M.x, y },
    thickness: 0.8,
    color: rgb(0.8, 0.82, 0.8),
  });
  y -= 18;
  const blockTop = y;
  page.drawText("Signature", { x: M.x, y, size: 11, font: bold, color: ink });
  y -= 15;
  const sigLines = input.signature
    ? [
        `Electronically approved and signed by ${input.signature.practitioner}`,
        `HPCSA registration number: ${input.signature.registrationNumber}`,
        `Method: ${ASSURANCE_LABELS[input.signature.assurance]} (${input.signature.method})`,
        `Signed: ${new Intl.DateTimeFormat("en-ZA", { dateStyle: "long", timeStyle: "short", timeZone: "Africa/Johannesburg" }).format(new Date(input.signature.signedAt))} (SAST)`,
        `Signature reference: ${input.signature.reference}`,
        ...(input.signature.assurance === "SIMPLE"
          ? [
              "This is a simple electronic signature, not an advanced or qualified electronic signature.",
            ]
          : []),
      ]
    : [
        "Signature status: PENDING. This document has not been signed and is not valid until it is.",
      ];
  const qrSize = 92;
  const textWidth = contentWidth - qrSize - 18;
  for (const line of sigLines.flatMap((l) => wrap(t(l), regular, 9, textWidth))) {
    page.drawText(line, { x: M.x, y, size: 9, font: regular, color: ink });
    y -= 12.5;
  }
  const qrBottom = blockTop - qrSize + 8;
  drawQr(page, input.verificationUrl, PAGE.w - M.x - qrSize, qrBottom, qrSize);
  y -= 8;
  page.drawText("Verify this document", { x: M.x, y, size: 9, font: bold, color: ink });
  y -= 12.5;
  for (const line of wrap(t(input.verificationUrl), regular, 8, textWidth)) {
    page.drawText(line, { x: M.x, y, size: 8, font: regular, color: muted });
    y -= 11;
  }

  // Footer on every page
  pages.forEach((p, i) => {
    p.drawText(FOOTER_TEXT, { x: M.x, y: 38, size: 7.5, font: regular, color: muted });
    p.drawText(t(`${input.documentId}  -  Page ${i + 1} of ${pages.length}`), {
      x: M.x,
      y: 27,
      size: 7.5,
      font: regular,
      color: muted,
    });
  });

  return pdf.save({ useObjectStreams: false, addDefaultPage: false });
}

// ---------------------------------------------------------------------------------------------
// Validation of any PDF we are about to store (including one returned by a signature provider)
// ---------------------------------------------------------------------------------------------

const FORBIDDEN_TOKENS = [
  "/JavaScript",
  "/JS ",
  "/Launch",
  "/EmbeddedFile",
  "/OpenAction",
  "/AA ",
  "/RichMedia",
];

export type PdfCheck = { ok: true; pages: number } | { ok: false; reason: string };

export async function validatePdf(bytes: Uint8Array): Promise<PdfCheck> {
  if (bytes.byteLength < 200 || bytes.byteLength > MAX_PDF_BYTES)
    return { ok: false, reason: "size" };
  const head = new TextDecoder("latin1").decode(bytes.subarray(0, 8));
  if (!head.startsWith("%PDF-1.") && !head.startsWith("%PDF-2."))
    return { ok: false, reason: "signature" };
  const tail = new TextDecoder("latin1").decode(
    bytes.subarray(Math.max(0, bytes.byteLength - 1100)),
  );
  if (!tail.includes("%%EOF")) return { ok: false, reason: "truncated" };
  const text = new TextDecoder("latin1").decode(bytes);
  for (const token of FORBIDDEN_TOKENS)
    if (text.includes(token)) return { ok: false, reason: "active_content" };
  try {
    const doc = await PDFDocument.load(bytes, { ignoreEncryption: false, updateMetadata: false });
    const pages = doc.getPageCount();
    return pages >= 1 && pages <= 50 ? { ok: true, pages } : { ok: false, reason: "pages" };
  } catch {
    return { ok: false, reason: "unparseable" };
  }
}
