/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveryPolicyRouteImport } from './routes/delivery-policy'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as MemberDocumentsRouteImport } from './routes/member.documents'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as SubscribeAdminApiRouteImport } from './routes/subscribe.admin-api'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as ApiPublicInventoryMaintenanceRouteImport } from './routes/api/public/inventory/maintenance'
import { Route as ApiPublicNewsroomRunRouteImport } from './routes/api/public/newsroom/run'
import { Route as ApiPublicNotificationsDispatchRouteImport } from './routes/api/public/notifications/dispatch'
import { Route as ApiPublicPaymentsPaypalWebhookRouteImport } from './routes/api/public/payments/paypal-webhook'
import { Route as ApiPublicPaymentsYocoWebhookRouteImport } from './routes/api/public/payments/yoco-webhook'
import { Route as ApiPublicSignaturesWebhookRouteImport } from './routes/api/public/signatures/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPolicyRoute = DeliveryPolicyRouteImport.update({
  id: '/delivery-policy',
  path: '/delivery-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDocumentsRoute = MemberDocumentsRouteImport.update({
  id: '/member/documents',
  path: '/member/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeAdminApiRoute = SubscribeAdminApiRouteImport.update({
  id: '/subscribe/admin-api',
  path: '/subscribe/admin-api',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInventoryMaintenanceRoute =
  ApiPublicInventoryMaintenanceRouteImport.update({
    id: '/api/public/inventory/maintenance',
    path: '/api/public/inventory/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsroomRunRoute = ApiPublicNewsroomRunRouteImport.update({
  id: '/api/public/newsroom/run',
  path: '/api/public/newsroom/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsDispatchRoute =
  ApiPublicNotificationsDispatchRouteImport.update({
    id: '/api/public/notifications/dispatch',
    path: '/api/public/notifications/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsPaypalWebhookRoute =
  ApiPublicPaymentsPaypalWebhookRouteImport.update({
    id: '/api/public/payments/paypal-webhook',
    path: '/api/public/payments/paypal-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsYocoWebhookRoute =
  ApiPublicPaymentsYocoWebhookRouteImport.update({
    id: '/api/public/payments/yoco-webhook',
    path: '/api/public/payments/yoco-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSignaturesWebhookRoute =
  ApiPublicSignaturesWebhookRouteImport.update({
    id: '/api/public/signatures/webhook',
    path: '/api/public/signatures/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/payment/return': typeof PaymentReturnRoute
  '/subscribe/admin-api': typeof SubscribeAdminApiRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/inventory/maintenance': typeof ApiPublicInventoryMaintenanceRoute
  '/api/public/newsroom/run': typeof ApiPublicNewsroomRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/api/public/payments/paypal-webhook': typeof ApiPublicPaymentsPaypalWebhookRoute
  '/api/public/payments/yoco-webhook': typeof ApiPublicPaymentsYocoWebhookRoute
  '/api/public/signatures/webhook': typeof ApiPublicSignaturesWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/payment/return': typeof PaymentReturnRoute
  '/subscribe/admin-api': typeof SubscribeAdminApiRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/journal': typeof JournalIndexRoute
  '/api/public/inventory/maintenance': typeof ApiPublicInventoryMaintenanceRoute
  '/api/public/newsroom/run': typeof ApiPublicNewsroomRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/api/public/payments/paypal-webhook': typeof ApiPublicPaymentsPaypalWebhookRoute
  '/api/public/payments/yoco-webhook': typeof ApiPublicPaymentsYocoWebhookRoute
  '/api/public/signatures/webhook': typeof ApiPublicSignaturesWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/delivery-policy': typeof DeliveryPolicyRoute
  '/doctor': typeof DoctorRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shop': typeof ShopRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/payment/return': typeof PaymentReturnRoute
  '/subscribe/admin-api': typeof SubscribeAdminApiRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/inventory/maintenance': typeof ApiPublicInventoryMaintenanceRoute
  '/api/public/newsroom/run': typeof ApiPublicNewsroomRunRoute
  '/api/public/notifications/dispatch': typeof ApiPublicNotificationsDispatchRoute
  '/api/public/payments/paypal-webhook': typeof ApiPublicPaymentsPaypalWebhookRoute
  '/api/public/payments/yoco-webhook': typeof ApiPublicPaymentsYocoWebhookRoute
  '/api/public/signatures/webhook': typeof ApiPublicSignaturesWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/delivery-policy'
    | '/doctor'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shop'
    | '/terms-of-service'
    | '/journal/$slug'
    | '/member/documents'
    | '/payment/return'
    | '/subscribe/admin-api'
    | '/verify/$token'
    | '/journal/'
    | '/api/public/inventory/maintenance'
    | '/api/public/newsroom/run'
    | '/api/public/notifications/dispatch'
    | '/api/public/payments/paypal-webhook'
    | '/api/public/payments/yoco-webhook'
    | '/api/public/signatures/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/delivery-policy'
    | '/doctor'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shop'
    | '/terms-of-service'
    | '/journal/$slug'
    | '/member/documents'
    | '/payment/return'
    | '/subscribe/admin-api'
    | '/verify/$token'
    | '/journal'
    | '/api/public/inventory/maintenance'
    | '/api/public/newsroom/run'
    | '/api/public/notifications/dispatch'
    | '/api/public/payments/paypal-webhook'
    | '/api/public/payments/yoco-webhook'
    | '/api/public/signatures/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/delivery-policy'
    | '/doctor'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shop'
    | '/terms-of-service'
    | '/journal/$slug'
    | '/member/documents'
    | '/payment/return'
    | '/subscribe/admin-api'
    | '/verify/$token'
    | '/journal/'
    | '/api/public/inventory/maintenance'
    | '/api/public/newsroom/run'
    | '/api/public/notifications/dispatch'
    | '/api/public/payments/paypal-webhook'
    | '/api/public/payments/yoco-webhook'
    | '/api/public/signatures/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryPolicyRoute: typeof DeliveryPolicyRoute
  DoctorRoute: typeof DoctorRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShopRoute: typeof ShopRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  JournalSlugRoute: typeof JournalSlugRoute
  MemberDocumentsRoute: typeof MemberDocumentsRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  SubscribeAdminApiRoute: typeof SubscribeAdminApiRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ApiPublicInventoryMaintenanceRoute: typeof ApiPublicInventoryMaintenanceRoute
  ApiPublicNewsroomRunRoute: typeof ApiPublicNewsroomRunRoute
  ApiPublicNotificationsDispatchRoute: typeof ApiPublicNotificationsDispatchRoute
  ApiPublicPaymentsPaypalWebhookRoute: typeof ApiPublicPaymentsPaypalWebhookRoute
  ApiPublicPaymentsYocoWebhookRoute: typeof ApiPublicPaymentsYocoWebhookRoute
  ApiPublicSignaturesWebhookRoute: typeof ApiPublicSignaturesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-policy': {
      id: '/delivery-policy'
      path: '/delivery-policy'
      fullPath: '/delivery-policy'
      preLoaderRoute: typeof DeliveryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/documents': {
      id: '/member/documents'
      path: '/member/documents'
      fullPath: '/member/documents'
      preLoaderRoute: typeof MemberDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/admin-api': {
      id: '/subscribe/admin-api'
      path: '/subscribe/admin-api'
      fullPath: '/subscribe/admin-api'
      preLoaderRoute: typeof SubscribeAdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inventory/maintenance': {
      id: '/api/public/inventory/maintenance'
      path: '/api/public/inventory/maintenance'
      fullPath: '/api/public/inventory/maintenance'
      preLoaderRoute: typeof ApiPublicInventoryMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsroom/run': {
      id: '/api/public/newsroom/run'
      path: '/api/public/newsroom/run'
      fullPath: '/api/public/newsroom/run'
      preLoaderRoute: typeof ApiPublicNewsroomRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/dispatch': {
      id: '/api/public/notifications/dispatch'
      path: '/api/public/notifications/dispatch'
      fullPath: '/api/public/notifications/dispatch'
      preLoaderRoute: typeof ApiPublicNotificationsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/paypal-webhook': {
      id: '/api/public/payments/paypal-webhook'
      path: '/api/public/payments/paypal-webhook'
      fullPath: '/api/public/payments/paypal-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPaypalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/yoco-webhook': {
      id: '/api/public/payments/yoco-webhook'
      path: '/api/public/payments/yoco-webhook'
      fullPath: '/api/public/payments/yoco-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsYocoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signatures/webhook': {
      id: '/api/public/signatures/webhook'
      path: '/api/public/signatures/webhook'
      fullPath: '/api/public/signatures/webhook'
      preLoaderRoute: typeof ApiPublicSignaturesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryPolicyRoute: DeliveryPolicyRoute,
  DoctorRoute: DoctorRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShopRoute: ShopRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  JournalSlugRoute: JournalSlugRoute,
  MemberDocumentsRoute: MemberDocumentsRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  SubscribeAdminApiRoute: SubscribeAdminApiRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  JournalIndexRoute: JournalIndexRoute,
  ApiPublicInventoryMaintenanceRoute: ApiPublicInventoryMaintenanceRoute,
  ApiPublicNewsroomRunRoute: ApiPublicNewsroomRunRoute,
  ApiPublicNotificationsDispatchRoute: ApiPublicNotificationsDispatchRoute,
  ApiPublicPaymentsPaypalWebhookRoute: ApiPublicPaymentsPaypalWebhookRoute,
  ApiPublicPaymentsYocoWebhookRoute: ApiPublicPaymentsYocoWebhookRoute,
  ApiPublicSignaturesWebhookRoute: ApiPublicSignaturesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
